# Generated by Django 5.1.3 on 2024-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
                ('group', models.ManyToManyField(related_name='groups', to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
